### ISSUE TITLE
When deploy in openEuler, the nginx-4180.service start failed about cannot open  libssl.so.10 and libcrypto.so.10

### ISSUE THREAD

**Issue by chenyz1984** [pingcap/tiunimanager#891]
`Oct 13 23:55:54 localhost.localdomain run_nginx.sh[70305]: bin/sbin/nginx: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

Oct 13 23:52:21 localhost.localdomain run_nginx.sh[70081]: bin/sbin/nginx: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
`

**Comment by haiboumich** [comment]
Currently, TiUniManager only supports Red Hat Enterprise Linux 7.3 and higher version and CentOS 7.3 and higher version.
Refer https://docs.pingcap.com/zh/tidb/stable/tiunimanager-install-and-maintain#tiunimanager-%E5%AE%89%E8%A3%85%E5%92%8C%E8%BF%90%E7%BB%B4%E6%8C%87%E5%8D%97
